# Generated by Django 5.2.1 on 2025-06-18 15:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bayouuser',
            name='favorite_artist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='music.artist'),
        ),
        migrations.AddField(
            model_name='bayouuser',
            name='liked_songs',
            field=models.ManyToManyField(blank=True, related_name='liked_by', to='music.song'),
        ),
    ]
