# Generated by Django 5.2.1 on 2025-06-05 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_remove_song_genre'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bayouuser',
            name='liked_songs',
            field=models.ManyToManyField(blank=True, related_name='liked_by', to='music.song'),
        ),
    ]
