# Generated by Django 5.2.1 on 2025-06-05 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_artist_genres_alter_song_cover'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='genre',
        ),
    ]
