# Generated by Django 5.2.1 on 2025-06-02 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_alter_song_artist_alter_song_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='cover',
            field=models.ImageField(blank=True, default='song_covers/default_cover.png', upload_to='song_covers/'),
        ),
    ]
