# Generated by Django 5.2.1 on 2025-06-10 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0005_recommendation'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to='song_audio/'),
        ),
        migrations.AlterField(
            model_name='song',
            name='duration',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
