# Generated by Django 5.2.1 on 2025-06-10 19:53

import music.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0006_song_audio_file_alter_song_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='audio_file',
            field=models.FileField(default=music.models.default_audio_file, upload_to='song_audio/'),
        ),
    ]
