# Generated by Django 5.2.1 on 2025-06-11 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0007_alter_song_audio_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='photo',
            field=models.ImageField(blank=True, default='artist_photos/default_artist.png', upload_to='artist_photos/'),
        ),
    ]
