# Generated by Django 5.2.1 on 2025-06-13 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0008_alter_artist_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='duration',
        ),
    ]
